### ISSUE TITLE
Calling and sms sending

### ISSUE THREAD

**Issue by PanosGr94** [tpakis/Charities#11]
Να υποθέσω πως θα γίνει μετα το πάτημα ενός κουμπιού; θα καλέσετε τις αντίστοιχες μεθόδους της κλάσης ανάλογα την περίπτωση;

**Comment by andreasagap** [comment]
Θεωρώ ότι μόλις πατάει στο εικονίδιο του τηλεφώνου ή του sms θα καλούνται οι μέθοδοι αλλά αυτό θα το δουν τα παιδιά του UI.
