### ISSUE TITLE
UI Recycler View (Adapter, Viewholder, Item List...)

### ISSUE THREAD

**Issue by NasiaKouts** [tpakis/Charities#3]
Καλησπέρα παιδιά!! Φτιάχνω το κομμάτι του UI σχετικά με το RV και CV. Θα προσπαθησω να τα ανεβασω μεχρι το βραδυ σημερα :D

**Comment by terpal** [comment]
Καλησπέρα @NasiaKouts. Επειδη κι εγώ έχω ξεκινήσει με το rv/cv, θα ήθελες να συννενοηθουμε και να μοιρασουμε δουλεια?

**Comment by NasiaKouts** [comment]
@terpal τωρα το ειδα. εγω κανει τα layout και τωρα θα ξεκινουσα τον adaptor
